var data = [
  "Bacon",
  "Grilled Pineapple",
  "Fried Egg",
  "Pesto",
  "Coleslaw",
  "Chili",
  "Sauteed Portabella Mushrooms",
  "Sauteed Peppers",
  "Goat Cheese",
  "Cheddar",
  "Jack",
  "Gorganzola",
  "Swiss",
  "American",
  "Mozzarella",
  "Virginia Ham",
  "Avocado",
  "Pepperoni",
  "Fried Egg",
  "Sliced Hot Chili Peppers",
  "Pickles",
  "Peanut Butter",
  "Jalapenos",
  "Marinara",
  "Jalapeno Popper"
];